; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rx

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1


[env:motorTest]
build_src_filter = 
    -<*>
    +<motorDriver.cpp>

[env:ultrasonicOtherTest]
lib_deps = 
    olikraus/U8g2
build_src_filter = 
    -<*>
    +<ultrasonicSensor.cpp>

[env:controllerTest]
build_src_filter = 
    -<*>
    +<controller.cpp>

[env:tx]
build_src_filter = 
    -<*>
    +<tx.cpp>

[env:rx]
build_src_filter = 
    -<*>
    +<rx.cpp>

[env:CarTest1]
build_src_filter = 
    -<*>
    +<main.cpp>
    +<controller.cpp>
    +<ultrasonicMaybe.cpp>


